apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: telegram-config
  namespace: monitoring
  labels:
    release: monitoring-stack # Khớp với label trong prometheus-stack-argocd.yaml
spec:
  route:
    receiver: 'telegram-receiver'
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
  receivers:
  - name: 'telegram-receiver'
    telegramConfigs:
    - botToken:
        name: telegram-secret
        key: bot-token
      chatID: -5148187096
      parseMode: 'HTML'
      sendResolved: true
