image:
  repository: asia-southeast1-docker.pkg.dev/nt114-q21/gout-llmops-repo/eval-orchestrator
  tag: "14725c9e9f3103d94f7960ceb3d84d0a4e4210c0"
containerPort: 8000
service:
  port: 8000
monitoring:
  enabled: true
envFromSecrets:
  - name: OPENAI_API_KEY
    secretName: openai-secret
    secretKey: OPENAI_API_KEY
