image:
  repository: asia-southeast1-docker.pkg.dev/macro-mender-494903-v0/gout-llmops-repo/eval-orchestrator
  tag: "80b26e7535f36229abe703c2bf661c32bed15d0c"
containerPort: 8000
service:
  port: 8000
resources:
  requests:
    memory: "512Mi"
    cpu: "200m"
  limits:
    memory: "2Gi"
    cpu: "1"

monitoring:
  enabled: true
envFromSecrets:
  - name: OPENAI_API_KEY
    secretName: openai-secret
    secretKey: OPENAI_API_KEY
