image:
  repository: asia-southeast1-docker.pkg.dev/nt114-q21/gout-llmops-repo/eval-orchestrator
  tag: "6e1dc18448191527683df315a518571097b26553"
containerPort: 8000
service:
  port: 8000
monitoring:
  enabled: true
envFromSecrets:
  - name: OPENAI_API_KEY
    secretName: openai-secret
    secretKey: OPENAI_API_KEY
