image:
  repository: asia-southeast1-docker.pkg.dev/macro-mender-494903-v0/gout-llmops-repo/gout-ui
  tag: "dae5584d20b82d55f65bca7ca7def726e8a26a01"
containerPort: 8501
service:
  port: 8501
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "500m"

monitoring:
  enabled: false
