image:
  repository: asia-southeast1-docker.pkg.dev/macro-mender-494903-v0/gout-llmops-repo/gout-ui
  tag: "2c0a0de7a601a9e310ed1c2ad1b37542cb48d439"
containerPort: 8501
service:
  port: 8501
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "500m"

monitoring:
  enabled: false
