image:
  repository: asia-southeast1-docker.pkg.dev/macro-mender-494903-v0/gout-llmops-repo/gout-ui
  tag: "39a247258ac992f6a31e247b9d926f67f38d9c30"
containerPort: 8501
service:
  type: NodePort
  port: 8501
  nodePort: 30080
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "500m"

monitoring:
  enabled: false
