apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.10.2
    chart: loki-stack
    helm:
      values: |
        loki:
          enabled: true
          # Cấu hình lưu trữ cơ bản cho môi trường nhỏ/vừa
          persistence:
            enabled: false
          datasource:
            isDefault: false
        promtail:
          enabled: true
        grafana:
          enabled: false # Tắt Grafana đi kèm vì chúng ta ĐÃ CÓ Grafana của Prometheus
        prometheus:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring # Cài chung nhà với Prometheus/Grafana cho dễ gọi nhau
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
