apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-ingestion-job
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ngantuyenhuynh/devops-gout-llmops.git'
    targetRevision: main
    path: k8s/data-ingestion
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gout-eval
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
