apiVersion: batch/v1
kind: Job
metadata:
  name: evaluation-job
  namespace: gout-eval
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: artifact-registry-key
      containers:
      - name: evaluation-job
        image: asia-southeast1-docker.pkg.dev/macro-mender-494903-v0/gout-llmops-repo/evaluation-job:2c0a0de7a601a9e310ed1c2ad1b37542cb48d439
        imagePullPolicy: Always
        env:
        - name: ORCHESTRATOR_URL
          value: http://eval-orchestrator-service.gout-eval.svc.cluster.local:8000/ask
        - name: TESTSET_PATH
          value: /app/data/gout_test_cases_mini.json
        - name: REQUEST_TIMEOUT
          value: "None"
        - name: JUDGE_MODEL
          value: gpt-4o-mini
        - name: EVAL_MODEL_NAME
          value: qwen2.5:1.5b
        - name: MAX_SAMPLES
          value: "3"
        - name: QUALITY_GATE_FAITHFULNESS_MIN
          value: "0.40"
        - name: QUALITY_GATE_COMPLETENESS_MIN
          value: "1.0"
        - name: QUALITY_GATE_RAGAS_FAITHFULNESS_MIN
          value: "0.30"
        - name: QUALITY_GATE_RAGAS_RELEVANCE_MIN
          value: "0.30"
        - name: QUALITY_GATE_RAGAS_CONTEXT_RECALL_MIN
          value: "0.60"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
