apiVersion: v1
kind: Service
metadata:
  name: gout-ui-service
  namespace: gout-eval
spec:
  type: LoadBalancer
  selector:
    app: gout-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
