apiVersion: v1
kind: Namespace
metadata:
  name: gout-eval
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eval-orchestrator
  namespace: gout-eval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eval-orchestrator
  template:
    metadata:
      labels:
        app: eval-orchestrator
    spec:
      containers:
      - name: backend
        image: asia-southeast1-docker.pkg.dev/logical-carver-490713-d8/gout-llmops-repo/eval-orchestrator:latest 
        ports:
        - containerPort: 80
