apiVersion: v1
kind: Namespace
metadata:
  name: gout-eval
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eval-orchestrator
  namespace: gout-eval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eval-orchestrator
  template:
    metadata:
      labels:
        app: eval-orchestrator
    spec:
      containers:
      - name: backend
        image: asia-southeast1-docker.pkg.dev/nt549-project/gout-llmops-repo/eval-orchestrator:latest 
        imagePullPolicy: Always   # <--- THÊM DÒNG NÀY ĐỂ ÉP KÉO CODE MỚI
        ports:
        - containerPort: 8000     # <--- SỬA 80 THÀNH 8000 CHO KHỚP VỚI DOCKERFILE
        env:
        - name: LANGFUSE_SECRET_KEY
          value: "sk-lf-..." # Điền secret key từ langfuse.com
        - name: LANGFUSE_PUBLIC_KEY
          value: "pk-lf-..." # Điền public key từ langfuse.com
        - name: LANGFUSE_HOST
          value: "https://cloud.langfuse.com"
