apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eval-orchestrator-monitor
  namespace: gout-eval
  labels:
    release: monitoring-stack 
spec:
  selector:
    matchLabels:
      app: eval-orchestrator
  namespaceSelector:
    matchNames:
      - gout-eval
      
  sampleLimit: 1000 
  
  endpoints:
  - port: http 
    path: /metrics
    interval: 60s 
    
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: '^python_gc_.*'
        action: drop
        
      - regex: '^client_ip|user_agent$'
        action: labeldrop
