apiVersion: batch/v1
kind: Job
metadata:
  name: gout-ingestion-job
  namespace: gout-eval
spec:
  template:
    spec:
      imagePullSecrets:
      - name: artifact-registry-key
      containers:
      - name: ingestion-container
        # Nhớ thay YOUR_PROJECT_ID bằng macro-mender-494903-v0
        image: asia-southeast1-docker.pkg.dev/macro-mender-494903-v0/gout-llmops-repo/data-ingestion:80b26e7535f36229abe703c2bf661c32bed15d0c
        imagePullPolicy: Always
      restartPolicy: OnFailure
  # Tự động xóa Job sau khi chạy xong 600 giây (10 phút) để pipeline kịp wait
  ttlSecondsAfterFinished: 600
