- name: Create namespaces
  shell: kubectl create namespace {{ item }} --dry-run=client -o yaml | kubectl apply -f -
  loop: "{{ namespaces }}"
  changed_when: true

# Cho phép các namespace pull image từ GCP Artifact Registry
- name: Create imagePullSecret in each namespace
  shell: >
    kubectl create secret docker-registry artifact-registry-key
    --docker-server={{ gcp_region }}-docker.pkg.dev
    --docker-username=_json_key
    --docker-password='{{ gcp_sa_key }}'
    --namespace={{ item }}
    --dry-run=client -o yaml | kubectl apply -f -
  loop: "{{ namespaces }}"
  changed_when: true
  vars:
    gcp_region: "{{ lookup('env', 'GCP_REGION') | default('asia-southeast1') }}"
    gcp_sa_key: "{{ lookup('env', 'GCP_SA_KEY') }}"
