- name: Create namespaces
  shell: kubectl create namespace {{ item }} --dry-run=client -o yaml | kubectl apply -f -
  loop: "{{ namespaces }}"
  changed_when: true

- name: Validate GCP SA key is provided
  fail:
    msg: "Thiếu biến gcp_sa_key. Chạy lại với: ansible-playbook ... -e gcp_sa_key=$(cat ~/sa-ansible-key.json)"
  when: gcp_sa_key is not defined or gcp_sa_key == ''

- name: Create imagePullSecret for Artifact Registry in each namespace
  shell: >
    kubectl create secret docker-registry artifact-registry-key
    --docker-server={{ gcp_region }}-docker.pkg.dev
    --docker-username=_json_key
    --docker-password='{{ gcp_sa_key }}'
    --namespace={{ item }}
    --dry-run=client -o yaml | kubectl apply -f -
  loop: "{{ namespaces }}"
  changed_when: true
  no_log: true
