- name: Create namespaces
  shell: kubectl create namespace {{ item }} --dry-run=client -o yaml | kubectl apply -f -
  loop: "{{ namespaces }}"
  changed_when: true

- name: Validate GCP SA key file is provided
  fail:
    msg: "Thiếu biến gcp_sa_key_file. Chạy lại với: ansible-playbook ... -e gcp_sa_key_file=~/sa-ansible-key.json"
  when: gcp_sa_key_file is not defined or gcp_sa_key_file == ''

- name: Create imagePullSecret for Artifact Registry in each namespace
  shell: >
    kubectl create secret docker-registry artifact-registry-key
    --docker-server={{ gcp_region }}-docker.pkg.dev
    --docker-username=_json_key
    --docker-password="$(cat {{ gcp_sa_key_file }})"
    --namespace={{ item }}
    --dry-run=client -o yaml | kubectl apply -f -
  loop: "{{ namespaces }}"
  changed_when: true
  no_log: true
