apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-worker
  namespace: gout-eval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-worker
  template:
    metadata:
      labels:
        app: ollama-worker
    spec:
      nodeSelector:
        role: worker-ai   # <--- Thêm dòng này để ghim pod vào vm3
      containers:
      - name: ollama
        image: ollama/ollama:0.6.2
        ports:
        - containerPort: 11434
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "5Gi"
            cpu: "1500m"