name: "CI: Build, Scan & Push Services"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'k8s/**'
      - '.github/workflows/ci.yaml'
      - '.github/workflows/reusable-build.yaml'
  pull_request:
    branches: [ "main" ]

jobs:
  # Xác định thư mục nào có thay đổi
  changes:
    name: "Detect File Changes"
    runs-on: ubuntu-latest
    outputs:
      orchestrator: ${{ steps.filter.outputs.orchestrator }}
      ui: ${{ steps.filter.outputs.ui }}
      ingestion: ${{ steps.filter.outputs.ingestion }}
      eval_job: ${{ steps.filter.outputs.eval_job }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            orchestrator:
              - 'src/eval-orchestrator/**'
              - 'k8s/eval-orchestrator-values.yaml'
            ui:
              - 'src/ui/**'
              - 'k8s/gout-ui-values.yaml'
            ingestion:
              - 'src/data-ingestion/**'
              - 'k8s/data-ingestion/**'
            eval_job:
              - 'src/evaluation-job/**'
              - 'k8s/evaluation-job/**'

  # Vẫn giữ nguyên quét mã nguồn
  security-audit:
    name: "Audit: Repository Security Scan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

  # GỌI KHUÔN ĐÚC CHO ORCHESTRATOR
  build-orchestrator:
    needs: [security-audit, changes]
    if: ${{ needs.changes.outputs.orchestrator == 'true' }}
    uses: ./.github/workflows/reusable-build.yaml
    with:
      service_name: "eval-orchestrator"
      build_context: "./src/eval-orchestrator"
      dockerfile_path: "./src/eval-orchestrator/Dockerfile"
    secrets: inherit # Tự động truyền toàn bộ secret xuống cho khuôn

  # GỌI KHUÔN ĐÚC CHO UI
  build-ui:
    needs: [security-audit, changes]
    if: ${{ needs.changes.outputs.ui == 'true' }}
    uses: ./.github/workflows/reusable-build.yaml
    with:
      service_name: "gout-ui"
      build_context: "./src/ui"
      dockerfile_path: "./src/ui/Dockerfile"
    secrets: inherit

  # GỌI KHUÔN ĐÚC CHO INGESTION
  build-ingestion:
    needs: [security-audit, changes]
    if: ${{ needs.changes.outputs.ingestion == 'true' }}
    uses: ./.github/workflows/reusable-build.yaml
    with:
      service_name: "data-ingestion"
      build_context: "."
      dockerfile_path: "./src/data-ingestion/Dockerfile"
    secrets: inherit

  # GỌI KHUÔN ĐÚC CHO EVAL JOB
  build-eval-job:
    needs: [security-audit, changes]
    if: ${{ needs.changes.outputs.eval_job == 'true' }}
    uses: ./.github/workflows/reusable-build.yaml
    with:
      service_name: "evaluation-job"
      build_context: "."
      dockerfile_path: "./src/evaluation-job/Dockerfile"
    secrets: inherit
